# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI

on:
  # schedule:
  #  - cron: 0 20 * * *
  release:
    types: [published]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:

  build_openwrt:

    permissions:
      contents: write # for release creation

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h

      - name: Update feeds
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          sed -i '$a src-git small8 https://github.com/kenzok8/small-package' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:
          # CONFIG_TARGET_IMAGES_GZIP=y
          # CONFIG_KERNEL_BUILD_USER="OpenWrt-CI"
          # CONFIG_KERNEL_BUILD_DOMAIN="Azure"
          cat >> .config <<EOF
          
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_PACKAGE_adguardhome=y
          CONFIG_PACKAGE_aliyundrive-fuse=y
          CONFIG_PACKAGE_aliyundrive-webdav=y
          CONFIG_PACKAGE_bash=y
          # CONFIG_PACKAGE_chinadns-ng is not set
          # CONFIG_PACKAGE_coreutils-base64 is not set
          CONFIG_PACKAGE_coreutils-nohup=y
          # CONFIG_PACKAGE_dns2socks is not set
          # CONFIG_PACKAGE_dns2tcp is not set
          CONFIG_PACKAGE_fuse-utils=y
          CONFIG_PACKAGE_iptvhelper=y
          CONFIG_PACKAGE_kmod-fuse=y
          CONFIG_PACKAGE_libcap-bin=y
          CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
          # CONFIG_PACKAGE_libcares is not set
          # CONFIG_PACKAGE_libev is not set
          CONFIG_PACKAGE_libfuse=y
          # CONFIG_PACKAGE_libmbedtls is not set
          CONFIG_PACKAGE_libruby=y
          # CONFIG_PACKAGE_libsodium is not set
          # CONFIG_PACKAGE_libudns is not set
          CONFIG_PACKAGE_libyaml=y
          # CONFIG_PACKAGE_lua-neturl is not set
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-advanced=y
          CONFIG_PACKAGE_luci-app-aliyundrive-fuse=y
          CONFIG_PACKAGE_luci-app-aliyundrive-webdav=y
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Socks_Server is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Trojan is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Xray is not set
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          CONFIG_PACKAGE_luci-app-iptvhelper=y
          CONFIG_PACKAGE_luci-app-openclash=y
          # CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_V2ray_Plugin is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-vlmcsd is not set
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Hysteria is not set
          # CONFIG_PACKAGE_luci-app-vssr_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Trojan is not set
          # CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray is not set
          # CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray_plugin is not set
          CONFIG_PACKAGE_luci-app-watchcat=m
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-i18n-adguardhome-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-aliyundrive-fuse-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-aliyundrive-webdav-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-iptvhelper-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-watchcat-zh-cn=m
          # CONFIG_PACKAGE_luci-lib-ipkg is not set
          # CONFIG_PACKAGE_microsocks is not set
          # CONFIG_PACKAGE_resolveip is not set
          CONFIG_PACKAGE_ruby=y
          CONFIG_PACKAGE_ruby-bigdecimal=y
          CONFIG_PACKAGE_ruby-date=y
          CONFIG_PACKAGE_ruby-digest=y
          CONFIG_PACKAGE_ruby-enc=y
          CONFIG_PACKAGE_ruby-forwardable=y
          CONFIG_PACKAGE_ruby-pstore=y
          CONFIG_PACKAGE_ruby-psych=y
          CONFIG_PACKAGE_ruby-stringio=y
          CONFIG_PACKAGE_ruby-strscan=y
          CONFIG_PACKAGE_ruby-yaml=y
          # CONFIG_PACKAGE_shadowsocks-libev-ss-local is not set
          # CONFIG_PACKAGE_shadowsocks-libev-ss-redir is not set
          # CONFIG_PACKAGE_shadowsocks-libev-ss-server is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-ssr-check is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-ssr-local is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-ssr-redir is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-ssr-server is not set
          # CONFIG_PACKAGE_simple-obfs is not set
          # CONFIG_PACKAGE_tcping is not set
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_vim-full=y
          CONFIG_PACKAGE_watchcat=m
          # CONFIG_PACKAGE_xray-core is not set
          CONFIG_PACKAGE_zsh=y
          CONFIG_TARGET_KERNEL_PARTSIZE=512
          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
          CONFIG_PACKAGE_adbyby=y
          CONFIG_PACKAGE_iptables-mod-ipsec=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-deflate=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-echainiv=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          # CONFIG_PACKAGE_kmod-inet-diag is not set
          # CONFIG_PACKAGE_kmod-ip-vti is not set
          # CONFIG_PACKAGE_kmod-ip6-vti is not set
          CONFIG_PACKAGE_kmod-ipsec=y
          CONFIG_PACKAGE_kmod-ipsec4=y
          CONFIG_PACKAGE_kmod-ipsec6=y
          CONFIG_PACKAGE_kmod-ipt-ipsec=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-iptunnel6=y
          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
          # CONFIG_PACKAGE_kmod-xfrm-interface is not set
          CONFIG_PACKAGE_strongswan=y
          CONFIG_PACKAGE_strongswan-charon=y
          # CONFIG_PACKAGE_strongswan-charon-cmd is not set
          # CONFIG_PACKAGE_strongswan-default is not set
          # CONFIG_PACKAGE_strongswan-gencerts is not set
          CONFIG_PACKAGE_strongswan-ipsec=y
          # CONFIG_PACKAGE_strongswan-isakmp is not set
          # CONFIG_PACKAGE_strongswan-libnttfft is not set
          # CONFIG_PACKAGE_strongswan-libtls is not set
          CONFIG_PACKAGE_strongswan-minimal=y
          # CONFIG_PACKAGE_strongswan-mod-addrblock is not set
          CONFIG_PACKAGE_strongswan-mod-aes=y
          # CONFIG_PACKAGE_strongswan-mod-af-alg is not set
          # CONFIG_PACKAGE_strongswan-mod-agent is not set
          # CONFIG_PACKAGE_strongswan-mod-attr is not set
          # CONFIG_PACKAGE_strongswan-mod-attr-sql is not set
          # CONFIG_PACKAGE_strongswan-mod-bliss is not set
          # CONFIG_PACKAGE_strongswan-mod-blowfish is not set
          # CONFIG_PACKAGE_strongswan-mod-ccm is not set
          # CONFIG_PACKAGE_strongswan-mod-chapoly is not set
          # CONFIG_PACKAGE_strongswan-mod-cmac is not set
          # CONFIG_PACKAGE_strongswan-mod-connmark is not set
          # CONFIG_PACKAGE_strongswan-mod-constraints is not set
          # CONFIG_PACKAGE_strongswan-mod-coupling is not set
          # CONFIG_PACKAGE_strongswan-mod-ctr is not set
          # CONFIG_PACKAGE_strongswan-mod-curl is not set
          # CONFIG_PACKAGE_strongswan-mod-curve25519 is not set
          # CONFIG_PACKAGE_strongswan-mod-des is not set
          # CONFIG_PACKAGE_strongswan-mod-dhcp is not set
          # CONFIG_PACKAGE_strongswan-mod-dnskey is not set
          # CONFIG_PACKAGE_strongswan-mod-duplicheck is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-identity is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-md5 is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-mschapv2 is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-radius is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-tls is not set
          # CONFIG_PACKAGE_strongswan-mod-farp is not set
          # CONFIG_PACKAGE_strongswan-mod-fips-prf is not set
          # CONFIG_PACKAGE_strongswan-mod-forecast is not set
          # CONFIG_PACKAGE_strongswan-mod-gcm is not set
          # CONFIG_PACKAGE_strongswan-mod-gcrypt is not set
          CONFIG_PACKAGE_strongswan-mod-gmp=y
          # CONFIG_PACKAGE_strongswan-mod-gmpdh is not set
          # CONFIG_PACKAGE_strongswan-mod-ha is not set
          CONFIG_PACKAGE_strongswan-mod-hmac=y
          CONFIG_PACKAGE_strongswan-mod-kernel-libipsec=y
          CONFIG_PACKAGE_strongswan-mod-kernel-netlink=y
          # CONFIG_PACKAGE_strongswan-mod-ldap is not set
          # CONFIG_PACKAGE_strongswan-mod-led is not set
          # CONFIG_PACKAGE_strongswan-mod-load-tester is not set
          # CONFIG_PACKAGE_strongswan-mod-md4 is not set
          # CONFIG_PACKAGE_strongswan-mod-md5 is not set
          # CONFIG_PACKAGE_strongswan-mod-mgf1 is not set
          # CONFIG_PACKAGE_strongswan-mod-mysql is not set
          # CONFIG_PACKAGE_strongswan-mod-newhope is not set
          CONFIG_PACKAGE_strongswan-mod-nonce=y
          # CONFIG_PACKAGE_strongswan-mod-ntru is not set
          # CONFIG_PACKAGE_strongswan-mod-openssl is not set
          # CONFIG_PACKAGE_strongswan-mod-pem is not set
          # CONFIG_PACKAGE_strongswan-mod-pgp is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs1 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs11 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs12 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs7 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs8 is not set
          CONFIG_PACKAGE_strongswan-mod-pubkey=y
          CONFIG_PACKAGE_strongswan-mod-random=y
          # CONFIG_PACKAGE_strongswan-mod-rc2 is not set
          # CONFIG_PACKAGE_strongswan-mod-resolve is not set
          # CONFIG_PACKAGE_strongswan-mod-revocation is not set
          CONFIG_PACKAGE_strongswan-mod-sha1=y
          # CONFIG_PACKAGE_strongswan-mod-sha2 is not set
          # CONFIG_PACKAGE_strongswan-mod-sha3 is not set
          # CONFIG_PACKAGE_strongswan-mod-smp is not set
          CONFIG_PACKAGE_strongswan-mod-socket-default=y
          # CONFIG_PACKAGE_strongswan-mod-socket-dynamic is not set
          # CONFIG_PACKAGE_strongswan-mod-sql is not set
          # CONFIG_PACKAGE_strongswan-mod-sqlite is not set
          # CONFIG_PACKAGE_strongswan-mod-sshkey is not set
          CONFIG_PACKAGE_strongswan-mod-stroke=y
          # CONFIG_PACKAGE_strongswan-mod-test-vectors is not set
          # CONFIG_PACKAGE_strongswan-mod-uci is not set
          # CONFIG_PACKAGE_strongswan-mod-unity is not set
          CONFIG_PACKAGE_strongswan-mod-updown=y
          # CONFIG_PACKAGE_strongswan-mod-vici is not set
          # CONFIG_PACKAGE_strongswan-mod-whitelist is not set
          CONFIG_PACKAGE_strongswan-mod-x509=y
          # CONFIG_PACKAGE_strongswan-mod-xauth-eap is not set
          CONFIG_PACKAGE_strongswan-mod-xauth-generic=y
          CONFIG_PACKAGE_strongswan-mod-xcbc=y
          # CONFIG_PACKAGE_strongswan-pki is not set
          # CONFIG_PACKAGE_strongswan-scepclient is not set
          # CONFIG_PACKAGE_strongswan-swanctl is not set
          CONFIG_PACKAGE_vlmcsd=y
          CONFIG_PACKAGE_vsftpd-alt=y
          # CONFIG_PACKAGE_xfrm is not set
          CONFIG_STRONGSWAN_ROUTING_TABLE="220"
          CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"
          CONFIG_VSFTPD_USE_UCI_SCRIPTS=y


          EOF
          #
          # ===============================================================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
  

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
